In [1]:
#import modules and print info about the dataset
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#mysql connector
import pymysql 
from sqlalchemy import create_engine
from urllib.parse import quote_plus
#postgresql connector
#psycopg2
#sqlalchemy
file_path='Walmart.csv'
df=pd.read_csv(file_path)
print(df.head())
print()
print(f"Dataset shape:{df.shape}")
df.describe()
df.info()

   invoice_id   Branch         City                category unit_price  \
0           1  WALM003  San Antonio       Health and beauty     $74.69
1           2  WALM048    Harlingen  Electronic accessories     $15.28
2           3  WALM067  Haltom City      Home and lifestyle     $46.33
3           4  WALM064      Bedford       Health and beauty     $58.22
4           5  WALM013       Irving       Sports and travel     $86.31

   quantity      date      time payment_method  rating  profit_margin
0       7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1       5.0  08/03/19  10:29:00           Cash     9.6           0.48
2       7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3       8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4       7.0  08/02/19  10:37:00        Ewallet     5.3           0.48

Dataset shape:(10051, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [2]:
#EDA: Duplicate rows & Missing values
print(f"Duplicate rows:{df.duplicated().sum()}")
print("Missing values:\n")
df.isnull().sum()

Duplicate rows:51
Missing values:

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [3]:
#Handle duplicate & missing values
df.drop_duplicates(inplace=True)
print(f"Duplicate rows:{df.duplicated().sum()}")
df.dropna(inplace=True) #drop missing values (or you could replace it with mean or mode depedning on the dataset)
df.isnull().sum()

Duplicate rows:0

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [4]:
#convert 'unit price' from object to integer
df['unit_price']=df['unit_price'].str.replace('$','').astype('float')
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [5]:
#add a new column of total price which is unit price * quantity
df['total_price']=df['unit_price']*df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [6]:
#mysql connection establishment
password = "Missi0810@"
pw = quote_plus(password)   
engine_mysql=create_engine(f"mysql+pymysql://root:{pw}@127.0.0.1:3306/walmart_db")

try:
    engine_mysql
    print("Connection established")
except:
    print("Connection interrupted")


try:
    conn = pymysql.connect(host='127.0.0.1', user='root', password='Missi0810@', port=3306)
    print("Connected!")
    conn.close()
except Exception as e:
    print("Connection failed:", e)

df.to_sql(
    name='walmart_db',    
    con=engine_mysql,   
    if_exists='replace',
    index=False        
)

print("DataFrame successfully exported to MySQL!")

Connection established
Connected!
DataFrame successfully exported to MySQL!

In [ ]:
#Business problems to solve in SQL
#1 Find different payment method, no of transactions in each & no. of qty sold.
#2 display the highest rated category in each branch and display the branch, category & avg rating of each.(for displaying highest category use rank method)
#3 identify the buisest day for each branch depending on the no of transactions.
#for postgres
'''SELECT
  branch,
  DAYNAME(STR_TO_DATE(`date`, '%d/%m/%y')) AS day_name,
  COUNT(*) AS no_transactions
FROM walmart_db
GROUP BY branch, day_name
ORDER BY branch, no_transactions;'''
#for sql
'''SELECT
  branch,
  DAYNAME(STR_TO_DATE(`date`, '%d/%m/%y')) AS day_name,
  COUNT(*) AS no_transactions
FROM walmart_db
GROUP BY branch, day_name
ORDER BY branch, no_transactions;
'''
#4 calculate the total profit for each category list category and total profit ordered highest to lowest